### ISSUE TITLE
API 样例

### ISSUE THREAD

**Issue by MournInk** [ZGIT-Network/OPENFRP-APIDOC#5]
在 **获取用户信息 API** 一节中，
给出的样例返回值为：
~~~json
"regTime": 1626512283.000000000
~~~
同时解释为：**注册时间（Unix 时间戳）**
然而实际请求时返回值为：
~~~json
"regTime": "2022-07-27 22:18:05"
~~~
> 我并没有测试 `https://of-dev-api.bfsea.xyz/`，但这个问题在 `https://api.openfrp.net/` 上存在。

**Comment by LxHTT** [comment]
Fixed in https://github.com/ZGIT-Network/OPENFRP-APIDOC/pull/7
