### ISSUE TITLE
API 请求示例错误

### ISSUE THREAD

**Issue by MournInk** [ZGIT-Network/OPENFRP-APIDOC#6]
在 **7. 编辑隧道** 中，请求示例的 `Payload`、解释、`Response` 均与 **4. 新建隧道** 相同。
即：**7. 编辑隧道** 的请求示例并不能按照预期的修改隧道。

**Comment by LxHTT** [comment]
Please check https://github.com/ZGIT-Network/OPENFRP-APIDOC/pull/7
